### ISSUE TITLE
What milestones should be created to group other issues more together?

### ISSUE THREAD

**Issue by secretsauceai** [secretsauceai/mfcc-rust#32]
# Description
We currently have 2 milestones here:
* [Create basic developer-friendly project management](https://github.com/secretsauceai/mfcc-rust/milestone/2)
* [Deliver MFCC rust MVP](https://github.com/secretsauceai/mfcc-rust/milestone/1)

As this project has been going on a while, it might be a good idea to have some more fine-grained tracking of the goals and deliverables of the project by creating additional milestones. 

## Questions
* What milestone(s) will group together the other issues nicely into smaller deliverables leading to the entire MVP?
* Which issues are in scope for which milestones?
* How can we ensure that the milestones are focused on working increments of deliverables that can be done within weeks to a couple of months?
* What does the definition of done (DoD) look like for the deliverables within the milestones? They should be clear and include: testing, documentation, user feedback, etc.

# DoD (Definition of Done)
- [ ] Above questions are answered
- [ ] The answers are implemented in the repo to create new milestones
- [ ] The issues are assigned to the milestones
